name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - setuptools=80.10.2
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.14.1
  - scikit-learn=1.4.2
  - matplotlib=3.10.8
  - flask=3.1.3
  - sqlalchemy=2.0.47
  - numba=0.64.0
  - opencv=4.11.0
  - pip:
    - tsfresh==0.20.3
    - mediapipe==0.10.18
    - flask-sqlalchemy==3.1.1
    - opencv-python==4.8.0.76
    - stumpy==1.14.1
    - statsmodels==0.14.6
    - jax==0.6.2
    - jaxlib==0.6.2
    - pyopenssl
